package de.uni_marburg.sp25.quality;

import de.uni_marburg.sp25.UserStory;
import java.util.List;

/**
 * Represents a quality issue identified during automated analysis of user stories.
 * 
 * QualityProblem serves as a standardized container for documenting quality violations
 * discovered by the various quality analysis algorithms. Each problem instance captures:
 * 
 * Problem Classification:
 * - criterionName: Which INVEST quality principle was violated
 * - problemType: Specific sub-category of the quality issue
 * - problemDescription: Human-readable explanation of the issue
 * - affectedStories: All user stories involved in this quality problem
 * 
 * Analysis Integration:
 * - Generated by QualityCriterion implementations during analysis
 * - Collected by QualityAnalysisManager for comprehensive reporting
 * - Displayed in UI with internationalized descriptions
 * - Exported in multiple formats (text, JSON) for external processing
 * 
 * Reporting Features:
 * - Supports localization through ResourceBundle integration
 * - Provides detailed problem context including story text
 * - Enables filtering and grouping by criterion or problem type
 * - Facilitates automated quality assurance workflows
 * 
 * Use Cases:
 * - Interactive quality feedback in the JavaFX UI
 * - Batch quality analysis reporting for development teams
 * - Integration with external tools through JSON export
 * - Quality metrics collection and trend analysis
 * 
 * @see QualityCriterion
 * @see QualityAnalysisManager
 * @see QualityAnalysisResult
 */
public class QualityProblem {
    /** Name of the quality criterion that identified this problem */
    private String criterionName;
    
    /** Detailed description of the quality issue in human-readable format */
    private String problemDescription;
    
    /** List of user stories affected by this quality problem */
    private List<UserStory> affectedStories;
    
    /** Specific type or category of the quality problem for classification */
    private String problemType;

    public QualityProblem(String criterionName, String problemDescription, List<UserStory> affectedStories, String problemType) {
        this.criterionName = criterionName;
        this.problemDescription = problemDescription;
        this.affectedStories = affectedStories;
        this.problemType = problemType;
    }

    // Getters and setters
    public String getCriterionName() { return criterionName; }
    public void setCriterionName(String criterionName) { this.criterionName = criterionName; }
    public String getProblemDescription() { return problemDescription; }
    public void setProblemDescription(String problemDescription) { this.problemDescription = problemDescription; }
    public List<UserStory> getAffectedStories() { return affectedStories; }
    public void setAffectedStories(List<UserStory> affectedStories) { this.affectedStories = affectedStories; }
    public String getProblemType() { return problemType; }
    public void setProblemType(String problemType) { this.problemType = problemType; }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Problem: ").append(problemDescription).append("\n");
        for (UserStory story : affectedStories) {
            sb.append("  User Story: ").append(story.getText()).append("\n");
        }
        return sb.toString();
    }
}
